apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marty-ingress
  namespace: marty
spec:
  ingressClassName: nginx
  rules:
    - host: vote.marty.ironhack.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: marty-svc-vote
                port:
                  number: 80
    - host: result.marty.ironhack.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: marty-svc-result
                port:
                  number: 80
